from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app import models, schemas, oauth2
from app.database import get_db
from typing import List

router = APIRouter(
    
    tags=["Applications"],
)

@router.post("/applications",status_code=status.HTTP_201_CREATED, response_model= schemas.ApplicationOut)
def create_application(application: schemas.ApplicationCreate, db: Session= Depends(get_db),current_user: models.User = Depends(oauth2.required_role(models.UserRole.CANDIDATE))):
    
    #first we verify that the job id is valid

    job =  db.query(models.Job).filter(models.Job.id==application.job_id).first()
    if not job:
        raise HTTPException(
                            status_code=status.HTTP_404_NOT_FOUND,
                            detail="the job id is not valid",
                        )

    # Check whether this candidate has already applied
    # to this particular job.
    existing_application = (
        db.query(models.Application)
        .filter(
            models.Application.candidate_id == current_user.id,
            models.Application.job_id == application.job_id,
        )
        .first()
    )

    if existing_application:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="You have already applied to this job",
        )

    applications=models.Application(# The candidate ID should come from the logged-in user,
                    # not from request data.
                    candidate_id=current_user.id,

                    # The job ID comes from the validated request.
                    job_id=application.job_id,

                    # Optional cover letter comes from the request body.
                    cover_letter=application.cover_letter,)
    
    db.add(applications)
    db.commit()
    db.refresh(applications)
    return {
    # Human-readable success message.
    "message": "Application is created successfully",

    # Application ID generated by PostgreSQL.
    "id": applications.id,

    # Job being applied to.
    "job_id": applications.job_id,

    # Logged-in candidate ID.
    "candidate_id": current_user.id,

    # Candidate username.
    "candidate_name": current_user.username,

    # Job details.
    "title": job.title,
    "location": job.location,

    # Convert the Enum to its string value.
    "status": applications.status.value,

    # Optional cover letter.
    "cover_letter": applications.cover_letter,
}
    

#now just for recruiter so he can see the applications for the jobs that he has created

@router.get("/applications/recruiter", status_code= status.HTTP_200_OK, response_model=List[schemas.ApplicationOut])
def get_applications_for_recruiter( db: Session= Depends(get_db), current_user: models.User= Depends(oauth2.required_role(models.UserRole.RECRUITER))):
    # Find every job created by the currently logged-in recruiter.
    recruiter_jobs = (
        db.query(models.Job)
        .filter(models.Job.created_by == current_user.id)
        .all()
    )

    # Extract only the IDs from those Job objects.
    #
    # Example:
    # recruiter_jobs = [Job(id=2), Job(id=5), Job(id=8)]
    #
    # becomes:
    # job_ids = [2, 5, 8]
    job_ids = [job.id for job in recruiter_jobs]

    # If the recruiter has not created any jobs,
    # there cannot be any applications for their jobs.
    if not job_ids:
        return []

    # Find every application whose job_id belongs
    # to one of the recruiter's jobs.
    applications = (
        db.query(models.Application)
        .filter(models.Application.job_id.in_(job_ids))
        .all()
    )

     # This list will contain the final response objects.
    response = []

    # applications is a list, so we process
    # each application individually.
    for application in applications:

        # Find the job associated with this application.
        job = (
            db.query(models.Job)
            .filter(models.Job.id == application.job_id)
            .first()
        )

        # Find the candidate who submitted this application.
        candidate = (
            db.query(models.User)
            .filter(models.User.id == application.candidate_id)
            .first()
        )

        # Add one ApplicationOut-compatible dictionary
        # to the response list.
        response.append(
            {
                "message": "Application retrieved successfully",

                # Application information.
                "id": application.id,
                "job_id": application.job_id,
                "candidate_id": application.candidate_id,

                # Candidate information.
                "candidate_name": candidate.username,

                # Job information.
                "title": job.title,
                "location": job.location,

                # Application information.
                "status": application.status.value,
                "cover_letter": application.cover_letter,
            }
        )

    return response

@router.patch("/applications/status-update/{application_id}", status_code= status.HTTP_200_OK, response_model= schemas.ApplicationOut)
def update_application_status(new_status: schemas.ApplicationUpdate, application_id: int, db: Session= Depends(get_db), current_user: models.User= Depends(oauth2.required_role(models.UserRole.RECRUITER))):

    #first we verify that the application being updated is for a job that was created by current recruiter

    
    
    application_query= db.query(models.Application).filter(models.Application.id==application_id).first()
    
    if application_query is None:
        raise HTTPException(status_code= status.HTTP_404_NOT_FOUND, detail =f"no application found with that ID")

    # Find the job this application belongs to.
    job = (
        db.query(models.Job)
        .filter(models.Job.id == application_query.job_id)
        .first()
    )

    # Make sure this recruiter actually created the job.
    if job.created_by != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You cannot update applications for this job",
        )

    # Update only the application status.
    application_query.status = new_status.status

    db.commit()
    db.refresh(application_query)

     # Find the candidate so we can include candidate_name
    # in the response.
    candidate = (
        db.query(models.User)
        .filter(models.User.id == application_query.candidate_id)
        .first()
    )

    # Return exactly what ApplicationOut expects.
    return {
        "message": "Application status updated successfully",
        "id": application_query.id,
        "job_id": application_query.job_id,
        "candidate_id": application_query.candidate_id,
        "candidate_name": candidate.username,
        "title": job.title,
        "location": job.location,
        "status": application_query.status.value,
        "cover_letter": application_query.cover_letter,
    }