from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app import models, schemas, oauth2
from app.database import get_db


router = APIRouter(
    
    tags=["Applications"],
)

@router.post("/applications",status_code=status.HTTP_201_CREATED, response_model= schemas.ApplicationOut)
def create_application(application: schemas.ApplicationCreate, db: Session= Depends(get_db),current_user: models.User = Depends(oauth2.required_role(models.UserRole.CANDIDATE))):
    
    #first we verify that the job id is valid

    job =  db.query(models.Job).filter(models.Job.id==application.job_id).first()
    if not job:
        raise HTTPException(
                            status_code=status.HTTP_404_NOT_FOUND,
                            detail="the job id is not valid",
                        )

    # Check whether this candidate has already applied
    # to this particular job.
    existing_application = (
        db.query(models.Application)
        .filter(
            models.Application.candidate_id == current_user.id,
            models.Application.job_id == application.job_id,
        )
        .first()
    )

    if existing_application:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="You have already applied to this job",
        )

    new_application=models.Application(# The candidate ID should come from the logged-in user,
                    # not from request data.
                    candidate_id=current_user.id,

                    # The job ID comes from the validated request.
                    job_id=application.job_id,

                    # Optional cover letter comes from the request body.
                    cover_letter=application.cover_letter,)
    
    db.add(new_application)
    db.commit()
    db.refresh(new_application)
    return {
    # Human-readable success message.
    "message": "Application is created successfully",

    # Application ID generated by PostgreSQL.
    "id": new_application.id,

    # Job being applied to.
    "job_id": new_application.job_id,

    # Logged-in candidate ID.
    "candidate_id": current_user.id,

    # Candidate username.
    "candidate_name": current_user.username,

    # Job details.
    "title": job.title,
    "location": job.location,

    # Convert the Enum to its string value.
    "status": new_application.status.value,

    # Optional cover letter.
    "cover_letter": new_application.cover_letter,
}
    

